name: Release npm package @smartive/stencil-react-ssr-output-target

on:
  push:
    branches:
      - main
      - next

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run build:stencil-react-ssr-output-target
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
          working_directory: ./packages/stencil-react-ssr-output-target
          extra_plugins: |
            @semantic-release/changelog@6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
